---
title: "infection_events"
output: html_document
date: '2022-04-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("reshape2","dplyr","dtplyr","data.table")
library("psych","ggplot2")
```

```{r}
infect <- data.table(read.csv("Infection_event_2021.csv"))
sensors <- data.table(read.csv("sensors_wd.csv"))
names(infect)[1:6] = c(
  "date",
  "infect_events",
  "avg_wet_hours_temp",
  "wet_hours",
  "humid_hours(90+)",
  "rain_amt_in"
)
```

```{r}
infect_days <-
  infect %>% filter(infect$infect_events == "yes" |
                      infect$infect_events == "combined")
```

```{r}
## North sites
n_main <- sensors %>% filter(site == "n.main")
n_m <- sensors %>% filter(site == "n.m")
n_e <- sensors %>% filter(site == "n.e")
n_x <- sensors %>% filter(site == "n.x")

## South sites
s_main <- sensors %>% filter(site == "s.main")
s_a11 <- sensors %>% filter(site == "s.a11")
s_a16 <- sensors %>% filter(site == "s.a16")
s_g <- sensors %>% filter(site == "s.g")
s_y <- sensors %>% filter(site == "s.y")
```

```{r}
ggplot(sensors[date == "2021-04-17",], 
       aes(time, rh, color = site)) + 
  geom_jitter(alpha = 0.9) + labs(title = "CSO parameters May 5th, 2021 (0:00-23:55)")

```

